### ISSUE TITLE
I have error "Undefined offset: 1" in this line

### ISSUE THREAD

**Issue by MaxCpp** [botstan/API#14]
https://github.com/botstan/API/blob/7981c4a166637e103531850c083d36ca3650ea73/src/keyboard/ReplyKeyboardMarkup.php#L88

Because if $ keyboard [$ row] is not exists, then sizeof () return error. If add check
`isset($keyboard[$row])`
this will work normal.

**Comment by mehdikhody** [comment]
Thanks for your notice.
[show me.](https://github.com/botstan/API/commit/02858fa1ef5e2334761ce58e3d7ff56480848ce8)
