### ISSUE TITLE
Array to string conversion #0

### ISSUE THREAD

**Issue by rogalev** [botstan/API#15]
```
$getUpdates = $api->getUpdates();
$getUpdates->limit = 1;
$getUpdates->allowed_updates = ['inline_query'];
$updates = $getUpdates->send();
```

PHP Notice 'yii\base\ErrorException' with message 'Array to string conversion'
in /app/yii-application/vendor/botstan/api/src/base/Curl.php:181

Stack trace:
#0 /app/yii-application/vendor/botstan/api/src/base/Curl.php(138): api\base\Curl->send()
#1 /app/yii-application/vendor/botstan/api/src/base/Request.php(196): api\base\Curl->post()
#2 /app/yii-application/vendor/botstan/api/src/method/Method.php(64): api\base\Request->send()

Request::send() use array_walk_recursive function which does not encode allowed_updates to JSON array

What if change current version of send() to

```
...
array_walk_recursive($params, function (&$value) {
    if ($value instanceof InputMedia && $value->media instanceof InputFile) {
        $media = $value->media;
        $fileName = $media->getFilename();
        $id = 'attached_' . md5($fileName);

        $this->set($id, $media);
        $value = $value->__array();
        $value['media'] = 'attach://' . $id;
    }
    if ($value instanceof Object) {
         $value = $value->__array();
    }
});

array_walk($params, function(&$value) {
    if (is_array($value)) {
        $value = Json::encode($value);
    }
});
```

**Comment by mehdikhody** [comment]
Thanks for your notice.
Please download our new release.
