### ISSUE TITLE
Webhook trouble

### ISSUE THREAD

**Issue by dozer111** [botstan/API#19]
Hi all.TG is my first learned bot, and this library is one which was on TG reccommends, and:
* i set hook by https://api.tg ......../setWebhook?url=......
But i don`t understand from yours documentation, how work with bots, which already webhook registered. 
All my tries goes to 500 Internal server error
Please, can you tell,what i must change in 
```
$token = '**********************';
$api = new \api\base\API($token);
$chatId = 123456;

$request = $api->sendMessage();
$request->chat_id = $chatId;
$request->text = 'simple text';
$response = $request->send();
```

to get Api object with chatId and other to do all the process automatical, like in simple PHP

**Comment by mehdikhody** [comment]
Hi,
Read #5.
