### ISSUE TITLE
class addressing, namespaces

### ISSUE THREAD

**Issue by dchetverikov** [botstan/API#2]
Hello. First of all - thank you for your project!

I guess in file api\src\method\Method.php it should be "use api\response\Response;" instead of "use yii\base\Response;", because I have an exception "isn't a response object", and only when I changed
"if ($class instanceof Response)" into "if ($class instanceof \api\response\Response)" in Method.php, the exception disappeared.

**Comment by mehdikhody** [comment]
Thank you, for your notice.
