### ISSUE TITLE
API->method() `$params` actually is `[$params]`

### ISSUE THREAD

**Issue by Vovan-VE** [botstan/API#20]
https://github.com/botstan/API/blob/25c929dcef69f1b4761203141d3b98314b0247ef/src/base/API.php#L170

Magic method `__call()` receives all actual arguments into single array, not variable number of arguments. But current implementation uses `$params` as the only argument. When we do:

```php
$api->sendMessage($config)
```

then new `sendMessage` object has the only property `0` containing whole `$config`.

The `API::__call()` will receive: `['sendMessage', [$config]]`.
As the result, the `Method`s constructor will be called as:

```php
return new $class($token, [$config]);
```

instead of expected:

```php
return new $class($token, $config);
```

To solve the issue, the line:
https://github.com/botstan/API/blob/25c929dcef69f1b4761203141d3b98314b0247ef/src/base/API.php#L178
must be:

```php
return new $className($this->token, ...$params);
```

This requires PHP >= 5.6, but current requirements are PHP >= 5.5.

**Comment by mehdikhody** [comment]
Thanks for your noticed

https://github.com/botstan/API/blob/7f2927e2edb257ca62037e4344a649816769599b/src/base/API.php#L178-L179

**Comment by Vovan-VE** [comment]
And now you break magic property `proxy` two lines above.

**Comment by Vovan-VE** [comment]
Why this magic internal property polutes data properties? Shouldn't it be separated to something like `protected $proxy`?
