### ISSUE TITLE
has and get doesnt work

### ISSUE THREAD

**Issue by taita-wizard** [botstan/API#4]
```
$api = new API($bot->token);
$request = $api->getMe();
$responseInfo = $request->send();

if(responseInfo->hasUsername()) // return false
$responseInfo->getUsername() // return null
```

**Comment by mehdikhody** [comment]
Initially, there was no error, but the Object.php file was edited several times,
and this problem occurred.

I repaired Object.php file and you can redownload library an use it.
Thanks for your notice.

**Comment by taita-wizard** [comment]
Thanks a lot
