### ISSUE TITLE
В связи с блокировкой телеги?

### ISSUE THREAD

**Issue by asminog** [botstan/API#9]
Exception 'yii\base\InvalidArgumentException' with message 'Syntax error.'

in /www/vendor/yiisoft/yii2/helpers/BaseJson.php:133

Stack trace:
#0 /www/vendor/yiisoft/yii2/helpers/BaseJson.php(107): yii\helpers\BaseJson::handleJsonError(4)
#1 /www/vendor/botstan/api/src/base/Curl.php(193): yii\helpers\BaseJson::decode(false)
#2 /www/vendor/botstan/api/src/base/Curl.php(138): api\base\Curl->send('POST', 'https://api.tel...', true)
#3 /www/vendor/botstan/api/src/base/Request.php(184): api\base\Curl->post('https://api.tel...', true)
#4 /www/vendor/botstan/api/src/method/Method.php(54): api\base\Request->send()

**Comment by asminog** [comment]
Нужен прокси

**Comment by mehdikhody** [comment]
Unfortunately Russia blocked Telegram, as you know. If your server located in this country, you must to use a proxy, please update to new release of this library.
```php
$api = new \api\base\API('<token>', [
    'server' => 'proxy.server.com',
    'port' => 8080,
    'auth' => 'user:pass'
]);

$api->sendMessage()
    ->setChatId('<chat_id>')
    ->setText('Hello World!!')
    ->send();
```
**or**
```php
$api->sendMessage()
    ->setProxy([
        'server' => 'proxy.server.com',
        'port' => 8080
    ])
    ->setChatId('<chat_id>')
    ->setText('Hello World!!')
    ->send();
```
